CREATE DATABASE HR_Database;


CREATE TABLE PERSON(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CODE VARCHAR(10),
TCNUMBER VARCHAR(11),
NAME_ VARCHAR(50),
SURNAME VARCHAR(50),
GENDER VARCHAR(1),
BIRTHDATE DATE,	
INDATE DATE,	
OUTDATE DATE,	
DEPARTMENTID INT,	
POSITIONID INT,	
PARENTPOSITIONID INT,	
MANAGERID INT,	
TELNR VARCHAR(15),	
SALARY FLOAT
);


CREATE TABLE POSITION(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
POSITION VARCHAR(50)
);

CREATE TABLE DEPARTMENT(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
DEPARTMENT VARCHAR(50)
);