USE ETRADE;


-- 1: Write an SQL query that retrieves the information about how many sales were made in which city on the ORDERSALES Table.

SELECT CITY, SUM(LINETOTAL) FROM SALEORDERS 
GROUP BY CITY
ORDER BY 1;


-- 2: Write a SQL query that retrieves the SALES ORDERS Table and how much sales were made in which month by city.

SELECT CITY, MONTH_, SUM(LINETOTAL) AS TOTALSALE 
FROM SALEORDERS
GROUP BY CITY, MONTH_
ORDER BY 1, 2;

-- 3: We want to find out on which day of the week we make the most sales in each city and make special campaigns for cities and days accordingly. 
-- Write the query that returns information on how much sales were made by the city according to the day of the week.

SELECT CITY, DAYOFWEEK_ , SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS 
GROUP BY CITY, DAYOFWEEK_
ORDER BY 1,2

-- 4: We want to find out which day of the week produces the most sales in each city and make special campaigns for cities and days accordingly. 
-- Write the query how much sales the cities make according to the days of the week.


SELECT CITY,
	(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE S.CITY = CITY AND DAYOFWEEK_ LIKE  '01%') AS PAZARTESI,
	(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE S.CITY = CITY AND DAYOFWEEK_ LIKE  '02%') AS SALI,
	(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE S.CITY = CITY AND DAYOFWEEK_ LIKE  '03%') AS CARSAMBA,
	(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE S.CITY = CITY AND DAYOFWEEK_ LIKE  '04%') AS PERSEMBE,
	(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE S.CITY = CITY AND DAYOFWEEK_ LIKE  '05%') AS CUMA,
	(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE S.CITY = CITY AND DAYOFWEEK_ LIKE  '06%') AS CUMARTESI,
	(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE S.CITY = CITY AND DAYOFWEEK_ LIKE  '07%') AS PAZAR
FROM SALEORDERS S
GROUP BY CITY
ORDER BY 1;


-- 5: Write the query that returns the top 5 best-selling categories of each province.


SELECT S.CITY, S1.CATEGORY1, SUM(S1.TOTALSALE) TOTALSALE

FROM SALEORDERS S
CROSS APPLY(SELECT TOP 5 CATEGORY1, SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS WHERE CITY = S.CITY GROUP BY CATEGORY1 ORDER BY 2 DESC) S1
GROUP BY S.CITY, S1.CATEGORY1
ORDER BY S.CITY, SUM(S1.TOTALSALE) DESC;


-- 6: Write a query that returns the 3 categories with the highest sales in each city and 
-- the 3 subcategories with the highest sales in each city.

SELECT S.CITY, S1.CATEGORY1, S2.CATEGORY2, SUM(S1.TOTALSALE) TOTALSALE
FROM SALEORDERS S
CROSS APPLY(SELECT TOP 3 CATEGORY1, SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS WHERE CITY = S.CITY GROUP BY CATEGORY1 ORDER BY 2 DESC) S1
CROSS APPLY(SELECT TOP 3 CATEGORY2, SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS WHERE CITY = S.CITY AND CATEGORY1=S1.CATEGORY1 GROUP BY CATEGORY2 ORDER BY 2 DESC) S2
GROUP BY S.CITY, S1.CATEGORY1, S1.CATEGORY1, S2.CATEGORY2
ORDER BY 1,2,4 DESC


-- 7: Create the SALEORDERS2 table by combining the tables with Join.

SET LANGUAGE TURKISH;

SELECT U.NAMESURNAME, U.TELNR1, U.TELNR2, CO.COUNTRY, C.CITY, T.TOWN, A.ADDRESSTEXT, O.ID

FROM USERS U
INNER JOIN ADDRESS A ON U.ID = A.USERID
INNER JOIN CITIES C ON A.CITYID = C.ID
INNER JOIN COUNTRIES CO ON C.COUNTRYID = CO.COUNTRY
INNER JOIN TOWNS T ON A.TOWNID = T.ID
INNER JOIN ORDERS O ON U.ID = O.USERID
;



SELECT TOP 10* FROM SALEORDERS;